### ISSUE TITLE
Smoke test javaVersionPrintsVendor fails on OpenJ9 JDK8 (all platforms)

### ISSUE THREAD

**Issue by adamfarley** [adoptium/temurin-build#2600] opened 2021-04-22 14:26 UTC
**What are you trying to do?**
Smoke test "javaVersionPrintsVendor" appears to be searching the output of "java -version" for a string that identifies the build vendor.

**Expected behaviour:**
The test appears to expect AdoptOpenJDK in the "java -version" output.

**Observed behaviour:**
The string "AdoptOpenJDK" is not present in the -version output, but only for OpenJ9 JDK8 (all platforms).

**Any other comments:**
This test is new, so it may be expecting something that was never intended to be there. 

Will consult with the wider community.

Examples:

https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-ppc64le-openj9_SmokeTests/6/console

```
13:52:11  openjdk version "1.8.0_292"
13:52:11  OpenJDK Runtime Environment (build 1.8.0_292-b09)
13:52:11  Eclipse OpenJ9 VM (build v0.26.0-release-b4cc246d9, JRE 1.8.0 Linux ppc64le-64-Bit Compressed References 20210417_940 (JIT enabled, AOT enabled)
13:52:11  OpenJ9   - b4cc246d9
13:52:11  OMR      - 162e6f729
13:52:11  JCL      - 7af75ceef39 based on jdk8u292-b09)
```

https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-s390x-openj9_SmokeTests/7/console

```
12:01:20  openjdk version "1.8.0_292"
12:01:20  OpenJDK Runtime Environment (build 1.8.0_292-b10)
12:01:20  Eclipse OpenJ9 VM (build openj9-0.26.0, JRE 1.8.0 Linux s390x-64-Bit Compressed References 20210421_957 (JIT enabled, AOT enabled)
12:01:20  OpenJ9   - b4cc246d9
12:01:20  OMR      - 162e6f729
12:01:20  JCL      - 2a5e2688142 based on jdk8u292-b10)
```

**Comment by sophia-guo** [comment] 2021-04-22 14:59
Is this duplicate of #2583

**Comment by pshipton** [comment] 2021-04-23 12:19
Looking at an older build, I don't think anything has changed.
```
openjdk version "1.8.0_272"
OpenJDK Runtime Environment (build 1.8.0_272-b10)
Eclipse OpenJ9 VM (build openj9-0.23.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20201022_822 (JIT enabled, AOT enabled)
OpenJ9   - 0394ef754
OMR      - 582366ae5
JCL      - 41f03341d5 based on jdk8u272-b10)
```

**Comment by smlambert** [comment] 2021-04-23 12:26
So we will change or remove that test from the ones that are valid for OpenJ9, thanks @pshipton

**Comment by pshipton** [comment] 2021-04-23 12:34
In Slack, this commit is mentioned https://github.com/AdoptOpenJDK/openjdk-jdk8u/commit/8b5839f7e70424197f4371f6654bdeaf862787ea

However that is something added to the Adopt repo, not something which is part of OpenJDK.
http://hg.openjdk.java.net/jdk8u/jdk8u/jdk/file/bbffc81f10de/src/share/classes/sun/misc/Version.java.template

**Comment by pshipton** [comment] 2021-04-23 12:39
To be more explicit, OpenJ9 builds with OpenJDK, and would only get this change if it's accepted into OpenJDK.

**Comment by adamfarley** [comment] 2021-04-29 09:41
Ok, I think the PR's ready: https://github.com/adoptium/temurin-build/pull/2602

@sophia-guo or @smlambert - Please review when you can.

**Closed** 2021-04-29 16:41 UTC
Labels: bug, openj9, testing
