### ISSUE TITLE
JDK`17 pipeline publish jobs failing

### ISSUE THREAD

**Issue by sxa** [adoptium/temurin-build#2732] opened 2021-09-30 08:54 UTC
**What are you trying to do?** Run successful [openjdk17-pipeline](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/) jobs overnight

**Expected behaviour:** Green blob against each job

**Observed behaviour:** Red blob against each job starting from September 24th run dur to "publish" step failing

**Any other comments:** Possibly related to https://github.com/adoptium/temurin-build/pull/2692

**Comment by gdams** [comment] 2021-09-30 09:14
So I rebuilt a failing release job and it passed (https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/refactor_openjdk_release_tool/4224/console).

Not sure what the issue is here (the errors suggest duplicate files but I don't see any).

I'll monitor this one for a few days and see if it happens again

**Comment by sxa** [comment] 2021-09-30 10:20
Since we've agreed to monitor it, I don't believe it's appropriate to close this until we've verified that it works through a full pipeline instead of just a re-run. Perhaps we should initiate an monitor a full JDK17 run during the day to do a full check?

**Comment by gdams** [comment] 2021-10-12 13:17
The last few builds have succedded. Closing

**Closed by gdams** 2021-10-12 13:17 UTC
