### ISSUE TITLE
A fatal error has been detected by the JRE version: OpenJDK Runtime Environment (11.0.5+10) (build 11.0.5+10)

### ISSUE THREAD

**Issue by DJreddy225** [adoptium/temurin-build#2682] opened 2021-08-03 03:27 UTC
The JBOSS App Server crashed with the below error, pls have a look.
[hs_err_pid68740_07Crash.txt](https://github.com/adoptium/temurin-build/files/6920824/hs_err_pid68740_07Crash.txt)

JBOSS EAP 7.2.4.

**Comment by tellison** [comment] 2021-08-03 08:17
Please can you try running with the latest Java update which is 11.0.12+7, available here (https://adoptium.net/releases.html)?

If it still fails let us know if it fails every time or only occasionally and any steps to reproduce the failure. Does it also fail with the system Java delivered with RHEL?

**Comment by jerboaa** [comment] 2021-08-03 09:12
This might be https://bugs.openjdk.java.net/browse/JDK-8251945 which should be fixed with 11.0.13+1 onwards (scheduled for October 2021). An EA build of that should be available soon. Once it's available - perhaps later this week. It would be worth giving it a try.

**Comment by DJreddy225** [comment] 2021-08-03 12:17
We are not able to reproduce the issue, it is failing once in a week. It has been failed 4 times in last one Month. In coming weeks August(14), we are planning for upgrading the JBOSS 7.2.4 to 7.3.2 and 11.0.8+10(Vendor Recommended).

is the issue still occur in 11.0.8+10?
Is the 11.0.8+10 is stable version?

Additional points below. 

1.	We are using the AdoptOpenJDK version of Java. For Sonata 9.12 we are using 11.0.5+10 and in Sonata 10.12 we are using 11.0.8+10. Below are extracts from a preproduction and production server showing the versions. 
2.	We are using Redhat 2.6.32-754.35.1.el6.x86_64, which I believe is 6.10 (Santiago)
3.	We had no plan to upgrade Linux as part of the Sonata 10.12 upgrade. I assumed it will be upgraded as part of the Unix upgrade maintenance plans. 

Please let me know if you need anything else.


PreProduction (Sonata 10.12)
$uname -a
Linux lhesona05v.production.local 2.6.32-754.35.1.el6.x86_64 #1 SMP Wed Sep 16 06:48:01 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.10 (Santiago)

$ cat /u01/app/\$ENV/Bravura/jboss-eap-7/version.txt
Red Hat JBoss Enterprise Application Platform - Version 7.3.2.GA

$ /u01/app/\$ENV/jre/bin/java -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)



Production (Sonata 9.12)
$uname -a
Linux lxpsona01v.production.local 2.6.32-754.35.1.el6.x86_64 #1 SMP Wed Sep 16 06:48:01 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.10 (Santiago)

$ cat /u01/app/\$ENV/Bravura/jboss-eap-7/version.txt
Red Hat JBoss Enterprise Application Platform - Version 7.2.4.GA

$ /u01/app/\$ENV/jre/bin/java -version
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.5+10, mixed mode)

**Comment by tellison** [comment] 2021-08-03 12:30
Thanks. Looks like a duplicate of https://github.com/adoptium/adoptium-support/issues/315

**Comment by DJreddy225** [comment] 2021-08-09 01:00
Can you provide the solution for the above pls.

Current One : 11.0.5+10 
Planning to upgrade 11.0.8+10 

We don't have any plans to go to other version.

**Comment by karianna** [comment] 2021-08-09 07:47
> Can you provide the solution for the above pls.
> 
> Current One : 11.0.5+10
> Planning to upgrade 11.0.8+10
> 
> We don't have any plans to go to other version.

You should upgrade to the latest 11.0.12 release.

**Closed by karianna** 2021-08-09 07:47 UTC
Labels: bug, duplicate

**Comment by DJreddy225** [comment] 2021-08-09 15:07
As per Vendor Suggestion we should go till 11.0.8+10.

1. Is the same JVM Crash errors will occur in 11.0.8+10?
2. How much stable is the version 11.0.8+10 against JBOSS 7.3.2?

**Comment by karianna** [comment] 2021-08-09 15:30
> As per Vendor Suggestion we should go till 11.0.8+10.
> 
> 1. Is the same JVM Crash errors will occur in 11.0.8+10?
> 2. How much stable is the version 11.0.8+10 against JBOSS 7.3.2?

You need to speak with your vendor again.  I suspect it's Red Hat in which case they'll likely be OK with you going to 11.0.12 (its hard to imagine JBoss won't run on that).

**Comment by DJreddy225** [comment] 2021-08-10 09:33
As per vendor supported documents they told AdoptOpen JDK can be used with 11.0.8+10.

So we are worrying that the JVM will be crashing for this as well.

**Comment by karianna** [comment] 2021-08-10 09:42
> As per vendor supported documents they told AdoptOpen JDK can be used with 11.0.8+10.
> 
> So we are worrying that the JVM will be crashing for this as well.

I'd recommend not just reading the vendor docs but actually having a conversation with them.

**Comment by DJreddy225** [comment] 2021-08-13 08:57
Okay will see.
