### ISSUE TITLE
Microsoft STL redistributable found in JDK is out of date

### ISSUE THREAD

**Issue by AndrewWinterAV** [adoptium/temurin-build#3887] opened 2024-07-11 15:57 UTC
### Please provide a brief summary of the bug

It was observed that an outdated version of msvcp140.dll located in the bin folder of installed JDKs. Microsoft published an update in June 2024 and an issue has arisen.

Specifically we have a c++ library being invoked from Java that uses a mutable const mutex that when compiled with the latest Microsoft toolset, crashes due to the mutex now being constructed inappropriately. The issue occurs when an attempt to lock the mutex takes place.

Is it possible to rebuild or repackage with the latest versions of the Microsoft redistributables.

### Did you test with the latest update version?

- [X] Yes

### Expected Results

msvcp140.dll is present with a minimum file version of 14.40.33810.0

### Actual Results

Current msvcp140.dll version is 14.36.32532.0

### What Java Version are you using?

openjdk 21.0.2 2024-01-16 LTS OpenJDK Runtime Environment Temurin-21.0.2+13 (build 21.0.2+13-LTS) OpenJDK 64-Bit Server VM Temurin-21.0.2+13 (build 21.0.2+13-LTS, mixed mode, sharing)

### What is your operating system and platform?

Windows 11

### How did you install Java?

msi

**Comment by sxa** [comment] 2024-07-15 08:39
Hi @AndrewHL76 - thanks for raising this. I think it's the first time I can recall such a failure reported with the C runtime in all my time with Adoptium/AdoptOpenJDK!

Can you confirm that if you swap in a later one into the JDK directory it works ok, making that a suitable workaround in the meantime? 

The tricky thing from our side is that for reproducibility reasons (if you're not aware, Tenurin is 100% binary reproducible) we typically don't always update the compilers to bleeding edge (as building with different versions makes them non reproducible), preferring fixed levels in general, but I appreciate that we may wish to look at an update with this specific failure. Having said that we will not be able to do anything in time for the PSU update this week unfortunately.

**Comment by DonOregano** [comment] 2024-07-16 21:30
I was bitten by this as well. And I put a newer msvcp140.dll into my temurin bin dir, and it works then. Would be awesome to have a fix for this soon-ish :-D
But the workaround works.

**Comment by AndrewHL76** [comment] 2024-07-18 18:00
A swap with newer binaries does indeed work, however this approach is not friendly to our deployment strategy.

@DonOregano Assuming they are your libraries, as an alternative work around you can use the preprocessor definition _DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR in your c++ projects that use the mutex class.

Ideally future distributions of JDK have the updated binaries

**Comment by DonOregano** [comment] 2024-07-18 22:49
Oh, thank you! That gives me a way to understand what is really going on here!

**Comment by sxa** [comment] 2024-07-19 07:18
> A swap with newer binaries does indeed work, however this approach is not friendly to our deployment strategy.

Yep agree that's far from ideal so will take a look at it options going forward on this one the current release cycle is complete. Thanks to both of you for confirming that we at least have a workaround for anyone else affected by this.

I'll also note for others who may be reading this that it is not specific to the MSI - the .zip downloads of Temurin also contain the runtime dll.

**Comment by nickwilliams-zaxiom** [comment] 2024-09-19 16:13
I wanted to add my voice here since our situation is a bit different: We have this exact same problem except that the `_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR` workaround does _not_ work for us (and we spent about a week of two developers' time trying to figure out why, but finally did).

The thing about `std::mutex::mutex()` being `constexpr` is that it makes it safe to use to guard the construction of static global objects. That means the mutex gets initialized early enough in DLL load that dynamic initializations can use the mutex also during DLL load. This is explained in [the documentation for this constructor](https://en.cppreference.com/w/cpp/thread/mutex/mutex):

>Because the default constructor is `constexpr`, static mutexes are initialized as part of [static non-local initialization](https://en.cppreference.com/w/cpp/language/initialization#Non-local_variables), before any dynamic non-local initialization begins. This makes it safe to lock a mutex in a constructor of any static object.

We use it for exactly this purpose. We were relieved to see `_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR` as a workaround and then immediately puzzled when it did not work—turns out it did, it just moved the problem. Now instead of our code being linked to an invalid memory address, our code is correctly linked but trying to lock an uninitialized mutex—because it's no longer `constexpr` and is getting initialized later in the DLL load.

We have been unable to find a palatable workaround for this. We cannot ask our users to remove `vcruntime140.dll` et. al. from (or replace it in) their JVM installations, because this would be "modifying" the JVM installation and many of our users are legally prohibited from "modifying" approved software. What we finally ended up doing—which horrified us—was adding `#if !defined( _WIN32 ) || defined( DEBUG )` around that specific lock and gambling on not having any multi-threaded issues during DLL load on Windows Opt platforms. (None of our other mutexes are locked during DLL load, so `_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR` worked for those cases.)

This problem is not exclusive to Temurin. We've now tried JVMs from three different vendors and they all have the same problem. It would be really great if all the JVM vendors could prioritize pushing out a patch with newer VC runtime DLLs.

**Closed** 2024-10-09 21:36 UTC
Labels: bug, testing

**Comment by xydwhaha** [comment] 2025-01-13 09:39
delete msvcp140.dll in jdk bin, I resolve this problem.

**Comment by borrrden** [comment] 2025-04-23 21:04
> It would be really great if all the JVM vendors could prioritize pushing out a patch with newer VC runtime DLLs.

Or even just have an option to not include it in the first place to allow the system one to be used.  Then an application installer can do what Microsoft actually recommends and run the visual c++ installer at install time to guarantee that a runtime is available.

**Comment by karianna** [comment] 2025-05-05 04:35
> > It would be really great if all the JVM vendors could prioritize pushing out a patch with newer VC runtime DLLs.
> 
> Or even just have an option to not include it in the first place to allow the system one to be used. Then an application installer can do what Microsoft actually recommends and run the visual c++ installer at install time to guarantee that a runtime is available.

We tend to keep it at a pinned version for reproducible builds
