### ISSUE TITLE
jdk11u-aix-ppc64-hotspot fails: "NUMBER_OF_FRAMES" is already defined with a different definition

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/temurin-build#2807] opened 2021-12-17 11:17 UTC
Thank you for reporting a broken build! Please fill in the following details:
- **Jenkins link to the failing log:** 
- https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-hotspot/1048/console
- **Which platforms (OS+arch) are affected:**
- AIX jdk11u
- **If you look at the historic logs, does the problem appear to be specific to one machine?**
- no
- **Link to any upstream project bug report (e.g. [OpenJ9](https://github.com/eclipse-openj9/openj9/issues)/[JBS](https://bugs.openjdk.java.net/browse))**

```
18:29:13  * For target support_test_hotspot_jtreg_native_support_libgetstacktr001_libgetstacktr001.o:
18:29:13  "./test/hotspot/jtreg/vmTestbase/nsk/jvmti/GetStackTrace/getstacktr001/getstacktr001.cpp", line 56.9: 1540-0848 (S) The macro name "NUMBER_OF_FRAMES" is already defined with a different definition.
18:29:13  "/usr/include/sys/mstsave.h", line 260.9: 1540-0425 (I) "NUMBER_OF_FRAMES" is defined on line 260 of "/usr/include/sys/mstsave.h".
```

**Comment by Haroon-Khel** [comment] 2021-12-17 15:57
https://bugs.openjdk.java.net/browse/JDK-8210205 Looks like a related upstream issue

**Comment by sxa** [comment] 2021-12-17 17:09
Yeah building the GA code looks ok https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-hotspot/1052/

**Comment by aixtools** [comment] 2021-12-21 01:06
As JDK-8210205 is from a few years back, and says resolved - does anyone inform them that something (similar) has happened again?

**Comment by andrew-m-leonard** [comment] 2021-12-22 09:14
@sxa @aixtools it looks like recent jdk11u commit 
https://github.com/adoptium/jdk11u/commit/4b591db099860cf0b1908cff960e0087d68385fc#diff-885e678e7440a0827db43a64233bb824587515d72a1822d5c6b93250443845f6
caused it, as in jdk-11.0.13 these files were built by the c compiler, which compiles NUMBER_OF_FRAMES fine.
I think the failure for NUMBER_OF_FRAMES only occurs with the cpp compiler.

**Comment by aixtools** [comment] 2021-12-22 10:25
Possible that it does not fail with a regular C compiler, which might explain why the recent change passed. But considering the the file extension is .cpp - I would think when using the C compiler the files are ignored - and that is why it passed.

Probably a better log/commit statement and/or an inline comment - to prevent a future regression.

**Comment by andrew-m-leonard** [comment] 2021-12-22 10:33
Looks like jdk11u C versions of the files (eg.getstacktr001.c) have always been NUMBER_OF_FRAMES, the fix in jdk(HEAD) http://hg.openjdk.java.net/jdk/jdk/rev/72291a181f8d should have been backported at the same time as changing C -> CPP

**Comment by aixtools** [comment] 2021-12-22 22:05
I did not look that deeply in the include files and see whether this macro was always visible, or only with c++ builds. At least this gives an idea to why the macro name was changed back. 
    	Get Outlook for iOS
    
  

 From: Andrew Leonard ***@***.***>Sent: Wednesday, December 22, 2021 11:34 AMTo: adoptium/temurin-buildCc: Michael Felt; MentionSubject: Re: [adoptium/temurin-build] jdk11u-aix-ppc64-hotspot fails: "NUMBER_OF_FRAMES" is already defined with a different definition (Issue #2807) 
Looks like jdk11u C versions of the files (eg.getstacktr001c) have always been NUMBER_OF_FRAMES, the fix in jdk(HEAD) http://hg.openjdk.java.net/jdk/jdk/rev/72291a181f8d should have been backported at the same time as changing C -> CPP

**Comment by sxa** [comment] 2021-12-29 15:58
Fix was [merged upstream](https://github.com/openjdk/jdk11u/commit/175e23fdf4cb0929ff1cca9538a884ee3833337d) and build 1058 https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-hotspot/ was successful, therefore closing this issue.

**Closed by sxa** 2021-12-29 15:58 UTC
Labels: macos, aix, openj9, testing, buildbreak, p-linux

**Comment by aixtools** [comment] 2021-12-29 17:01
Hurrah, just in time!
