### ISSUE TITLE
Update CentOS mirrorlink

### ISSUE THREAD

**Issue by smlambert** [adoptium/temurin-build#3905] opened 2024-08-06 13:13 UTC
https://ci.adoptium.net/job/Test_openjdk23_hs_special.system_x86-64_linux/7/

Current test is trying to use CentOS 7 which no longer exists

```
docker run -v "/home/jenkins/workspace/Test_openjdk23_hs_special.system_x86-64_linux_rerun/aqa-tests/TKG/../../jvmtest/system/reproducibleCompare:/home/jenkins/test" -w "/home/jenkins/" -v "/home/jenkins/workspace/Test_openjdk23_hs_special.system_x86-64_linux_rerun/jdkbinary/j2sdk-image/jdk-23+35/bin/../:/home/jenkins/jdkbinary/" --name reproducibleCompare centos:7 /bin/bash /home/jenkins/test/linux_repro_build_compare.sh /home/jenkins/test/OpenJDK23U-sbom_x64_linux_hotspot_23_35-ea.json /home/jenkins/jdkbinary; \
[2024-08-02T04:48:53.423Z] if [ $? -eq 0 ]; then echo "-----------------------------------"; echo "Rebuild_Same_JDK_Reproducibility_Test_0""_PASSED"; echo "-----------------------------------"; cd /home/jenkins/workspace/Test_openjdk23_hs_special.system_x86-64_linux_rerun/aqa-tests/TKG/..; rm -f -r "/home/jenkins/workspace/Test_openjdk23_hs_special.system_x86-64_linux_rerun/aqa-tests/TKG/../TKG/output_17225741323010/Rebuild_Same_JDK_Reproducibility_Test_0"; else echo "-----------------------------------"; echo "Rebuild_Same_JDK_Reproducibility_Test_0""_FAILED"; echo "-----------------------------------"; fi; \
[2024-08-02T04:48:53.423Z] docker cp reproducibleCompare:/home/jenkins/reprotest.diff ./; \
[2024-08-02T04:48:53.423Z] docker cp reproducibleCompare:/home/jenkins/reproJDK.tar.gz ./; \
[2024-08-02T04:48:53.423Z] docker cp reproducibleCompare:/home/jenkins/SBOM.json ./; \
[2024-08-02T04:48:53.423Z] docker container rm reproducibleCompare; \
[2024-08-02T04:48:53.423Z] echo "";	echo "TEST TEARDOWN:"; \
[2024-08-02T04:48:53.423Z] echo "Nothing to be done for teardown."; \
[2024-08-02T04:48:53.423Z]  } 2>&1 | tee -a "/home/jenkins/workspace/Test_openjdk23_hs_special.system_x86-64_linux_rerun/aqa-tests/TKG/../TKG/output_17225741323010/TestTargetResult";
[2024-08-02T04:48:53.423Z] 
[2024-08-02T04:48:53.423Z] TEST SETUP:
[2024-08-02T04:48:53.423Z] Nothing to be done for setup.
[2024-08-02T04:48:53.423Z] 
[2024-08-02T04:48:53.423Z] TESTING:
[2024-08-02T04:48:54.091Z] Error: No such container: reproducibleCompare
[2024-08-02T04:48:56.260Z] Loaded plugins: fastestmirror, ovl
[2024-08-02T04:48:56.260Z] Determining fastest mirrors
[2024-08-02T04:48:56.260Z] Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=container error was
[2024-08-02T04:48:56.260Z] 14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
[2024-08-02T04:48:56.260Z] 
[2024-08-02T04:48:56.260Z] 
[2024-08-02T04:48:56.260Z]  One of the configured repositories failed (Unknown),
[2024-08-02T04:48:56.260Z]  and yum doesn't have enough cached data to continue. At this point the only
[2024-08-02T04:48:56.260Z]  safe thing yum can do is fail. There are a few ways to work "fix" this:
[2024-08-02T04:48:56.260Z] 
[2024-08-02T04:48:56.260Z]      1. Contact the upstream for the repository and get them to fix the problem.
[2024-08-02T04:48:56.260Z] 
[2024-08-02T04:48:56.260Z]      2. Reconfigure the baseurl/etc. for the repository, to point to a working
[2024-08-02T04:48:56.260Z]         upstream. This is most often useful if you are using a newer
[2024-08-02T04:48:56.260Z]         distribution release than is supported by the repository (and the
[2024-08-02T04:48:56.260Z]         packages for the previous distribution release still work).
[2024-08-02T04:48:56.260Z] 
[2024-08-02T04:48:56.260Z]      3. Run the command with the repository temporarily disabled
[2024-08-02T04:48:56.260Z]             yum --disablerepo=<repoid> ...
[2024-08-02T04:48:56.260Z] 
[2024-08-02T04:48:56.260Z]      4. Disable the repository permanently, so yum won't use it by default. Yum
[2024-08-02T04:48:56.260Z]         will then just ignore the repository until you permanently enable it
[2024-08-02T04:48:56.260Z]         again or use --enablerepo for temporary usage:
[2024-08-02T04:48:56.260Z] 
[2024-08-02T04:48:56.260Z]             yum-config-manager --disable <repoid>
[2024-08-02T04:48:56.260Z]         or
[2024-08-02T04:48:56.260Z]             subscription-manager repos --disable=<repoid>
[2024-08-02T04:48:56.260Z] 
[2024-08-02T04:48:56.260Z]      5. Configure the failing repository to be skipped, if it is unavailable.
[2024-08-02T04:48:56.260Z]         Note that yum will try to contact the repo. when it runs most commands,
[2024-08-02T04:48:56.260Z]         so will have to try and fail each time (and thus. yum will be be much
[2024-08-02T04:48:56.260Z]         slower). If it is a very temporary problem though, this is often a nice
[2024-08-02T04:48:56.260Z]         compromise:
[2024-08-02T04:48:56.260Z] 
[2024-08-02T04:48:56.260Z]             yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true
[2024-08-02T04:48:56.260Z] 
[2024-08-02T04:48:56.260Z] Cannot find a valid baseurl for repo: base/7/x86_64
[2024-08-02T04:48:56.928Z] -----------------------------------
[2024-08-02T04:48:56.928Z] Rebuild_Same_JDK_Reproducibility_Test_0_FAILED
[2024-08-02T04:48:56.928Z] -----------------------------------
```

**Comment by sxa** [comment] 2024-08-12 12:45
This will need the repositories switched to `vault.centos.org` - see https://github.com/adoptium/infrastructure/pull/3643/files for an example.

**Comment by smlambert** [comment] 2024-08-16 11:43
I believe Andrew mentioned we should move to CentOS 8, but I see his recent blog post instructions at https://adoptium.net/docs/reproducible-verification-builds/reproduce-linux-x64/ reference both

<img width="800" alt="Screenshot 2024-08-16 at 7 43 13 AM" src="https://github.com/user-attachments/assets/fd137d51-121f-480c-bfcf-47b673b4b1c8">

**Comment by sxa** [comment] 2024-08-16 12:28
> I believe Andrew mentioned we should move to CentOS 8

We could but bear in mind that CentOS8 also went out of support some time ago (the dates for each are [on the infrastructure wiki](https://github.com/adoptium/infrastructure/wiki/End-of-support-date-for-OS-distributions) - there ~~is~~was only the "moving target" of CentOS Stream 8 that's available from that project now, but that is also now out of support as of May (So I guess that isn't really a moving target any more, but CentOS Stream in general is) So TL;DR: Moving to 8 isn't any better than sticking with 7 at this point.

Since we have the devkit we can potentially use almost anything for this (including CentOS Stream 8 but that seems like a pointless move as per the previous paragraph), but IMHO the easiest change to allow this to work is just to use the vault links with CentOS7, which is what we're doing elsewhere.

> Do we need to move to ubi?

To be clear, we don't /need/ to move to anything, since the use the vault mirror will allow us to continue using CentOS7, and that is stable (very stable - it will never receive any further updates!). I have tested using a devkit on UBI9 at https://github.com/adoptium/temurin-build/issues/3847#issuecomment-2161273298 so that is also an option, however [a later comment in that issue](https://github.com/adoptium/temurin-build/issues/3847#issuecomment-2162921583) suggests it wasn't able to reproduce the main builds.

**Comment by sophia-guo** [comment] 2024-08-16 14:33
Yes, CentOS 8 reached EOL on December 31, 2021 and CentOS 7 - June 30, 2024 https://www.centos.org/centos-linux-eol/.

**Comment by sophia-guo** [comment] 2024-08-16 15:00
Images are also deprecated https://hub.docker.com/_/centos

**Closed** 2024-08-18 23:56 UTC
Labels: enhancement, docker, jenkins, testing
